# Generated by Django 5.0 on 2023-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('week', models.IntegerField(db_index=True)),
                ('day', models.IntegerField(db_index=True)),
                ('booked_slot', models.BooleanField(default=False)),
                ('user_id', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'time_slots',
                'indexes': [models.Index(fields=['user_id'], name='user_id_idx')],
            },
        ),
    ]
